# fly.toml app configuration file generated for litefs on 2024-01-26T12:34:34+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "litefs"
primary_region = "cdg"

[build]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

# [http_service]
#   internal_port = 8080
#   force_https = true
#   auto_stop_machines = true
#   auto_start_machines = true
#   min_machines_running = 0

[mounts]
  source = "litefs"
  destination = "/var/lib/litefs"